# Generated by Django 4.2.8 on 2024-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentByChatGPT',
            field=models.BooleanField(null=True),
        ),
    ]
